"""add external_id and time_periods to company dsa

Revision ID: 00ff0dc07583
Revises: f33fdeb7c9d5
Create Date: 2026-09-06 15:09:18.103542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00ff0dc07583'
down_revision: Union[str, None] = 'f33fdeb7c9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_questions', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_company_questions_external_id'), 'company_questions', ['external_id'], unique=False)
    op.add_column('dsa_company_questions', sa.Column('time_periods', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('dsa_company_questions', sa.Column('source_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dsa_company_questions', 'source_file')
    op.drop_column('dsa_company_questions', 'time_periods')
    op.drop_index(op.f('ix_company_questions_external_id'), table_name='company_questions')
    op.drop_column('company_questions', 'external_id')
    # ### end Alembic commands ###
