"""add profile fields to user

Revision ID: 0d041b5dbaf7
Revises: b79233263d58
Create Date: 2026-07-15 14:59:53.288525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d041b5dbaf7'
down_revision: Union[str, None] = 'b79233263d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('branch', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'branch')
    op.drop_column('users', 'college')
    # ### end Alembic commands ###
