"""add intelligence fields to companies

Revision ID: a1a6c5ac325a
Revises: 0d041b5dbaf7
Create Date: 2026-08-28 22:35:25.577545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a6c5ac325a'
down_revision: Union[str, None] = '0d041b5dbaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('tier_category', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('preparation_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'source_metadata')
    op.drop_column('companies', 'preparation_topics')
    op.drop_column('companies', 'difficulty')
    op.drop_column('companies', 'tier_category')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
