"""Add notes to roadmap topic

Revision ID: b79233263d58
Revises: 227bd9995668
Create Date: 2026-07-13 18:39:44.936187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79233263d58'
down_revision: Union[str, None] = '227bd9995668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_topics', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_topics', 'notes')
    # ### end Alembic commands ###
