"""create company_questions and user_question_progress tables

Revision ID: f04c6c6092ba
Revises: a1a6c5ac325a
Create Date: 2026-08-29 12:26:19.445011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f04c6c6092ba'
down_revision: Union[str, None] = 'a1a6c5ac325a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('platform_url', sa.String(), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('companies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_count', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_questions_id'), 'company_questions', ['id'], unique=False)
    op.create_index(op.f('ix_company_questions_slug'), 'company_questions', ['slug'], unique=True)
    op.create_index(op.f('ix_company_questions_title'), 'company_questions', ['title'], unique=False)
    op.create_table('user_question_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['company_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_progress')
    )
    op.create_index(op.f('ix_user_question_progress_id'), 'user_question_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_question_progress_question_id'), 'user_question_progress', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_question_progress_user_id'), 'user_question_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_question_progress_user_id'), table_name='user_question_progress')
    op.drop_index(op.f('ix_user_question_progress_question_id'), table_name='user_question_progress')
    op.drop_index(op.f('ix_user_question_progress_id'), table_name='user_question_progress')
    op.drop_table('user_question_progress')
    op.drop_index(op.f('ix_company_questions_title'), table_name='company_questions')
    op.drop_index(op.f('ix_company_questions_slug'), table_name='company_questions')
    op.drop_index(op.f('ix_company_questions_id'), table_name='company_questions')
    op.drop_table('company_questions')
    # ### end Alembic commands ###
