"""create dsa_companies dsa_company_questions goal_companies

Revision ID: f33fdeb7c9d5
Revises: f04c6c6092ba
Create Date: 2026-08-29 13:03:28.289118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33fdeb7c9d5'
down_revision: Union[str, None] = 'f04c6c6092ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsa_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('is_top_30', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsa_companies_id'), 'dsa_companies', ['id'], unique=False)
    op.create_index(op.f('ix_dsa_companies_name'), 'dsa_companies', ['name'], unique=True)
    op.create_index(op.f('ix_dsa_companies_slug'), 'dsa_companies', ['slug'], unique=True)
    op.create_table('dsa_company_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['dsa_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['company_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'question_id', name='uq_dsa_company_question')
    )
    op.create_index(op.f('ix_dsa_company_questions_company_id'), 'dsa_company_questions', ['company_id'], unique=False)
    op.create_index(op.f('ix_dsa_company_questions_id'), 'dsa_company_questions', ['id'], unique=False)
    op.create_index(op.f('ix_dsa_company_questions_question_id'), 'dsa_company_questions', ['question_id'], unique=False)
    op.create_table('goal_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['dsa_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'company_id', name='uq_goal_company')
    )
    op.create_index(op.f('ix_goal_companies_company_id'), 'goal_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_goal_companies_goal_id'), 'goal_companies', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_companies_id'), 'goal_companies', ['id'], unique=False)
    op.add_column('company_questions', sa.Column('source_dataset', sa.String(), server_default='MERGED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_questions', 'source_dataset')
    op.drop_index(op.f('ix_goal_companies_id'), table_name='goal_companies')
    op.drop_index(op.f('ix_goal_companies_goal_id'), table_name='goal_companies')
    op.drop_index(op.f('ix_goal_companies_company_id'), table_name='goal_companies')
    op.drop_table('goal_companies')
    op.drop_index(op.f('ix_dsa_company_questions_question_id'), table_name='dsa_company_questions')
    op.drop_index(op.f('ix_dsa_company_questions_id'), table_name='dsa_company_questions')
    op.drop_index(op.f('ix_dsa_company_questions_company_id'), table_name='dsa_company_questions')
    op.drop_table('dsa_company_questions')
    op.drop_index(op.f('ix_dsa_companies_slug'), table_name='dsa_companies')
    op.drop_index(op.f('ix_dsa_companies_name'), table_name='dsa_companies')
    op.drop_index(op.f('ix_dsa_companies_id'), table_name='dsa_companies')
    op.drop_table('dsa_companies')
    # ### end Alembic commands ###
